### ISSUE TITLE
GetPlayerAchievements return List<Player>

### ISSUE THREAD

**Issue by Lorac** [just0rz/wg-api-sharp-library#4]
At line 400 in WGApplication.cs, I'm wondering why you are returning List<Player> when we are trying to use the method for one player in particular. Shouldn't return List<Achievements> ?

**Comment by just0rz** [comment]
I'll take a look and get back to you.

**Comment by just0rz** [comment]
I think the issue is that if you send a list of account ids(players)  you get a list of players with Achievements list populated for each player. 
Anyway i noticed that i forgot to remove the NotImplementedException at the end :) OR i didn't merge the branch where i have that fixed yet. 

I agree that it's a little confusing maybe i need to add a bit more details. 

If you have any suggestions feel free to implement it and i'll merge it.

I'll leave this open until it gets clarified.

**Comment by just0rz** [comment]
http://eu.wargaming.net/developers/api_reference/wot/account/achievements/

This is the API reference.

**Comment by Lorac** [comment]
Well I can understand that If you send an array of accountIds it makes sense to return a list of players with acheivements list populated. But I saw a method call GetPlayerAchievements with one accountID so I though it would return the list of acheivements for that player.

So I guess it's not implemented like that for now or it's a working as design?

**Comment by just0rz** [comment]
I think you are right. I could return the list of Achievements if the request is only for one accountid or I could return a Player with its achievements populated.  I see your point.

**Comment by Lorac** [comment]
Well given the method name I would return a List<Achievements>.
